[workspace]
resolver = "2"

members = [
    "day1",
    "day2",
    "day3",
    "day4",
    "day5", "day6",
    "lib"
]

[workspace.dependencies]
itertools = { version = "0.13.0" }
winnow = { version = "0.6.20" }
anyhow = "1.0.94"