[package]
name = "day13"
version = "0.1.0"
edition = "2021"

[dependencies]
rstest = { workspace = true }
anyhow = { workspace = true }
winnow = { workspace = true }
itertools = { workspace = true }
insta = { workspace = true }
gcd = { workspace = true }
lib = { path = "../lib" }