[package]
name = "day7"
version = "0.1.0"
edition = "2021"

[dependencies]
winnow = { workspace = true }
itertools = { workspace = true }
rstest = { workspace = true }
rayon = { workspace = true }
lib = { path = "../lib" }